services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container-new
    environment:
      MYSQL_ROOT_PASSWORD: jRAP00yylnMyHi0
      MYSQL_DATABASE: finance
    healthcheck:
      # Check if MySQL is ready by running "mysqladmin ping"
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pjRAP00yylnMyHi0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  finance:
    image: financeapp:latest
    container_name: finance-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/finance?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: jRAP00yylnMyHi0
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


