services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-new
    environment:
      MYSQL_ROOT_PASSWORD: jRAP00yylnMyHi0
      MYSQL_DATABASE: finance
    networks:
      - mynetwork

  finance:
    build: .
    container_name: finance-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container-new:3306/finance?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: jRAP00yylnMyHi0
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
